backplane:
  redisUri: "redis://localhost:6379"
  queues:
    - name: "cpu"
      properties:
        - name: "min-cores"
          value: "*"
        - name: "max-cores"
          value: "*"
        - name: "persistentWorkerKey"
          value: "*"
        - name: "persistentWorkerCommand"
          value: "*"
worker:
  publicName: "localhost:8981"
  dequeueMatchSettings:
    allowUnmatched: true
    properties:
      - name: "persistentWorkerKey"
        value: "*"
      - name: "persistentWorkerCommand"
        value: "*"

