name: Build and Push Base Buildfarm Worker Images
# Following the HOWTO at https://docs.docker.com/build/ci/github-actions/multi-platform/

on:
  push:
    branches:
      - main
    paths:
      - ci/base-worker-image/jammy/Dockerfile
      - ci/base-worker-image/mantic/Dockerfile
jobs:
  build:
    if: github.repository == 'bazelbuild/bazel-buildfarm'
    name: Build Base Buildfarm Worker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # QEMU needed for the ARM variant.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Docker Buildx needed for the ARM variant.

      - name: Login to Bazelbuild Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

      - name: Build Jammy Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          file: ./ci/base-worker-image/jammy/Dockerfile
          push: true
          tags: bazelbuild/buildfarm-worker-base:jammy

      - name: Build Mantic Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          file: ./ci/base-worker-image/mantic/Dockerfile
          push: true
          tags: bazelbuild/buildfarm-worker-base:mantic
